# Use official PyTorch image with CUDA runtime
FROM pytorch/pytorch:2.1.0-cuda12.2-cudnn8-runtime

# Set working directory
WORKDIR /app

# Copy requirements
COPY ../requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY ../src ./src

# Expose FastAPI port
EXPOSE 8000

# Run FastAPI
CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000"]
